/**
 * Charades: no banned words. These are acted, not described, so there is no
 * obvious word to forbid.
 */
module.exports = {
  slug: 'act-it-out',
  name: 'Act It Out',
  description: 'Stepping on a Lego, getting left on read, a mime stuck in a box. No talking, all drama.',
  accentColor: '#9B5CFF',
  emoji: '🎭',
  tags: ['actions', 'charades'],
  createdAt: '2026-07-26T18:00:00Z',
  updatedAt: '2026-10-07T22:00:00Z',
  cards: [
    'Stepping on a Lego',
    'Parallel parking', 'Losing your keys', 'Winning the lottery', 'Sneezing',
    'Running for a bus', 'Blowing out candles', 'Stubbing your toe', 'Taking a selfie',
    'Waking up late', 'Riding a horse', 'Getting a haircut', 'Being tickled',
    'Swatting a fly', 'Falling asleep in a meeting', 'Opening a stuck jar', 'Brushing your teeth',
    'Juggling', 'Eating something too hot', 'Pretending to like a gift', 'Sneaking in late',
    'Getting caught in the rain', 'Arm wrestling', 'Chasing a runaway dog', 'Applying sunscreen',
    'Blowing up a balloon', 'Wrapping a present badly', 'Trying to open a door that says pull',
    'Untangling headphones', 'Playing air guitar', 'Miming through a window', 'Pretending to be asleep',
    'Doing a TikTok dance',
    'Taking a BeReal',
    'Getting left on read',
    'Walking into a glass door',
    'Getting brain freeze',
    'Doing the worm',
    'Moonwalking',
    'Losing your phone in your bed',
    'Hitting snooze five times',
    'Pretending to text to avoid someone',
    'Building IKEA furniture',
    'Riding a mechanical bull',
    'Surfing a huge wave',
    'Skateboarding',
    'Snowboarding',
    'Ice skating for the first time',
    'Riding a roller coaster',
    'Walking through a haunted house',
    'Doing a cartwheel',
    'Doing yoga',
    'Lifting weights at the gym',
    'Running on a treadmill',
    'Sumo wrestling',
    'Bowling a strike',
    'Swinging a golf club',
    'Shooting a free throw',
    'Taking a penalty kick',
    'Rock climbing',
    'Bungee jumping',
    'Skydiving',
    'Milking a cow',
    'Walking a dog that won’t move',
    'Giving a cat a bath',
    'Changing a diaper',
    'Putting on skinny jeans',
    'Doing makeup in a moving car',
    'Blowing a bubble with gum',
    'Doing a magic trick',
    'A mime trapped in a box',
    'Conducting an orchestra',
    'DJing at a party',
    'Playing the drums',
    'Singing opera',
    'Walking a runway',
    'Taking a group photo',
    'Photobombing',
    'Proposing on one knee',
    'Catching the bouquet',
    'Running from a bee',
    'Walking like a zombie',
    'Being a T. rex',
    'Doing the robot',
    'Studying the night before finals',
    'Waiting for your food to arrive',
    'Scrolling your phone at 3am',
    'Looking for phone signal',
    'Rage quitting a video game',
    'Giving an award speech',
    'Dodging the paparazzi',
    'Eating a really sour candy',
    'Opening a ketchup packet',
    'Getting caught singing in the car',
    'Fainting dramatically',
    'Slipping on a banana peel',
    'Walking on hot sand',
    'Jumping into a cold pool',
    'Finding a spider in the shower',
    'Carrying every grocery bag in one trip',
  ],
};
