module.exports = {
  slug: 'animals',
  name: 'Animals',
  description: 'From the obvious to the ones nobody can describe without flapping.',
  accentColor: '#00C2B2',
  tags: ['nature', 'easy'],
  createdAt: '2026-07-26T18:00:00Z',
  updatedAt: '2026-10-07T20:00:00Z',
  cards: [
    'Elephant | trunk, tusks, big, grey',
    'Penguin | tuxedo, ice, waddle, Antarctica',
    'Octopus | tentacles, eight, ink, sea',
    'Kangaroo | Australia, jump, pouch, joey',
    'Sloth | slow, tree, lazy, hang',
    'Flamingo | pink, one leg, bird, lawn',
    'Hedgehog | spikes, prickly, Sonic, ball',
    'Giraffe | neck, tall, spots, leaves',
    'Platypus | duck, beaver, Australia, eggs',
    'Jellyfish | sting, sea, wobbly, see-through',
    'Chameleon | colour, change, lizard, tongue',
    'Walrus | tusks, moustache, Arctic, flippers',
    'Meerkat | stand up, desert, Timon, lookout',
    'Porcupine | quills, spikes, prickly, rodent',
    'Otter | river, hold hands, swim, cute',
    'Rhinoceros | horn, grey, Africa, charge',
    'Peacock | feathers, tail, fan, blue',
    'Armadillo | shell, armour, ball, Texas',
    'Hippopotamus | river, huge, mouth, Africa',
    'Koala | Australia, eucalyptus, bear, tree',
    'Woodpecker | peck, tree, beak, knock',
    'Tarantula | spider, hairy, eight legs, scary',
    'Seahorse | horse, sea, father, tail',
    'Ostrich | bird, fast, head in sand, egg',
    'Panda | bamboo, black and white, China, bear',
    'Crocodile | teeth, river, snap, alligator',
    'Bat | night, wings, cave, vampire',
    'Snail | shell, slow, slime, garden',
    'Camel | hump, desert, water, ride',
    'Skunk | smell, stink, black and white, spray',
    'Lobster | claws, red, seafood, pinch',
    'Toucan | beak, colourful, bird, rainforest',
    'Badger | stripe, honey, burrow, nocturnal',
    'Squid | tentacles, ink, calamari, sea',
    'Gorilla | ape, chest, silverback, King Kong',
    'Pelican | beak, pouch, fish, bird',
    'Ferret | weasel, pet, sneaky, long',
    'Moose | antlers, Canada, elk, big',
    'Starfish | five, arms, beach, Patrick',
    'Beaver | dam, teeth, wood, tail',
    'Vulture | circling, bird, desert, bald',
    'Llama | spit, wool, Peru, alpaca',
    'Racoon | bins, mask, trash panda, night',
    'Swan | white, lake, ballet, neck',
    'Cheetah | fast, spots, run, cat',
    'Hamster | wheel, pet, cheeks, cage',
    'Owl | hoot, night, wise, Hedwig',
    'Dolphin | Flipper, smart, sea, clicks',
    'Wombat | Australia, burrow, cube, marsupial',
    'Praying mantis | pray, green, insect, arms',
  ],
};
