module.exports = {
  slug: 'animals',
  name: 'Animals',
  description: 'Capybaras, angry geese and everything in between. Flapping, honking and crawling strongly encouraged.',
  accentColor: '#00C2B2',
  emoji: '🦁',
  tags: ['nature', 'easy'],
  createdAt: '2026-07-26T18:00:00Z',
  updatedAt: '2026-10-07T22:00:00Z',
  cards: [
    'Capybara | chill, giant rodent, South America, hot tub',
    'Elephant | trunk, tusks, big, grey',
    'Penguin | tuxedo, ice, waddle, Antarctica',
    'Octopus | tentacles, eight, ink, sea',
    'Kangaroo | Australia, jump, pouch, joey',
    'Sloth | slow, tree, lazy, hang',
    'Flamingo | pink, one leg, bird, lawn',
    'Hedgehog | spikes, prickly, Sonic, ball',
    'Giraffe | neck, tall, spots, leaves',
    'Platypus | duck, beaver, Australia, eggs',
    'Jellyfish | sting, sea, wobbly, see-through',
    'Chameleon | colour, change, lizard, tongue',
    'Walrus | tusks, moustache, Arctic, flippers',
    'Meerkat | stand up, desert, Timon, lookout',
    'Porcupine | quills, spikes, prickly, rodent',
    'Otter | river, hold hands, swim, cute',
    'Rhinoceros | horn, grey, Africa, charge',
    'Peacock | feathers, tail, fan, blue',
    'Armadillo | shell, armour, ball, Texas',
    'Hippopotamus | river, huge, mouth, Africa',
    'Koala | Australia, eucalyptus, bear, tree',
    'Tarantula | spider, hairy, eight legs, scary',
    'Seahorse | horse, sea, father, tail',
    'Ostrich | bird, fast, head in sand, egg',
    'Panda | bamboo, black and white, China, bear',
    'Crocodile | teeth, river, snap, alligator',
    'Bat | night, wings, cave, vampire',
    'Snail | shell, slow, slime, garden',
    'Camel | hump, desert, water, ride',
    'Skunk | smell, stink, black and white, spray',
    'Lobster | claws, red, seafood, pinch',
    'Toucan | beak, colourful, bird, rainforest',
    'Squid | tentacles, ink, calamari, sea',
    'Gorilla | ape, chest, silverback, King Kong',
    'Moose | antlers, Canada, elk, big',
    'Starfish | five, arms, beach, Patrick',
    'Beaver | dam, teeth, wood, tail',
    'Llama | spit, wool, Peru, alpaca',
    'Cheetah | fast, spots, run, cat',
    'Hamster | wheel, pet, cheeks, cage',
    'Owl | hoot, night, wise, Hedwig',
    'Dolphin | Flipper, smart, sea, clicks',
    'Wombat | Australia, burrow, cube, marsupial',
    'Praying mantis | pray, green, insect, arms',
    'Axolotl | pink, smile, salamander, Mexico',
    'Quokka | happiest animal, smile, Australia, selfie',
    'Honey badger | fearless, doesn’t care, snakes, Africa',
    'Narwhal | unicorn, horn, whale, Arctic',
    'Red panda | fluffy, bamboo, Firefox, orange',
    'Pufferfish | inflate, spiky, balloon, poison',
    'Pigeon | city, coo, bread, statue',
    'Goose | honk, angry, Canada, chase',
    'Raccoon | trash panda, bins, mask, night',
    'Shark | Jaws, teeth, fin, ocean',
    'Blobfish | ugly, deep sea, pink, sad',
    'Corgi | short legs, Queen, fluffy, dog',
    'Golden retriever | dog, fetch, loyal, boyfriend',
    'Pug | wrinkly, snort, flat face, dog',
    'Guinea pig | squeak, pet, rodent, cage',
    'Alpaca | Peru, llama, wool, fluffy',
    'Seal | flippers, clap, ball, ocean',
    'Polar bear | Arctic, white, ice, Coca-Cola',
    'Bald eagle | America, bird, wings, symbol',
    'Parrot | talk, pirate, colourful, copy',
    'Gecko | lizard, Geico, wall, sticky',
    'Komodo dragon | lizard, Indonesia, giant, venom',
    'Tiger | stripes, Tony, big cat, orange',
    'Lion | roar, mane, king, Simba',
    'Zebra | stripes, horse, black and white, Africa',
    'Wolf | howl, moon, pack, husky',
    'Fox | red, sly, tail, ring-ding-ding',
    'Bunny | Easter, hop, carrot, rabbit',
    'Squirrel | nuts, tree, tail, acorn',
    'Chihuahua | tiny, dog, Mexico, shaking',
    'Frog | ribbit, lily pad, green, prince',
    'Chicken | cluck, egg, farm, nuggets',
    'Cow | moo, milk, farm, spots',
    'Pig | oink, mud, bacon, farm',
    'Goat | baa, horns, cheese, farm',
    'Donkey | Shrek, ears, hee-haw, stubborn',
    'Duck | quack, pond, bread, feathers',
    'Bee | buzz, honey, sting, hive',
    'Butterfly | wings, caterpillar, colourful, flutter',
    'Mosquito | bite, itchy, buzz, summer',
    'Cockroach | gross, survive, kitchen, bug',
    'Scorpion | tail, sting, desert, claws',
    'Hummingbird | tiny, wings, fast, nectar',
    'Ladybug | red, spots, bug, lucky',
    'Manatee | sea cow, slow, Florida, chubby',
    'Orca | killer whale, Free Willy, black and white, ocean',
    'Stingray | flat, tail, sting, ocean',
    'Crab | claws, sideways, beach, Sebastian',
    'Clownfish | Nemo, orange, anemone, stripes',
    'Hyena | laugh, scavenger, Lion King, spots',
    'Sea turtle | shell, ocean, beach, slow',
    'Dachshund | sausage dog, long, short legs, wiener',
    'Husky | blue eyes, snow, sled, howl',
    'Horse | neigh, ride, gallop, saddle',
    'Sheep | baa, wool, flock, count',
    'Mouse | cheese, squeak, tiny, Mickey',
  ],
};
