module.exports = {
  slug: 'celebrities',
  name: 'Celebrities',
  description: 'Movie stars, comedians, creators and icons. Do the impression; everyone will know.',
  accentColor: '#9B5CFF',
  emoji: '⭐',
  tags: ['celebrities', 'pop culture'],
  createdAt: '2026-10-07T22:00:00Z',
  updatedAt: '2026-10-07T22:00:00Z',
  cards: [
    'Zendaya | Euphoria, Spider-Man, Dune, Disney',
    'Timothée Chalamet | Dune, Wonka, Call Me by Your Name, French',
    'Tom Holland | Spider-Man, British, Zendaya, Uncharted',
    'Margot Robbie | Barbie, Australian, Harley Quinn, Wolf of Wall Street',
    'Ryan Gosling | Ken, Barbie, The Notebook, La La Land',
    'Ryan Reynolds | Deadpool, Canadian, sarcastic, Wrexham',
    'Dwayne Johnson | The Rock, eyebrow, wrestler, Moana',
    'Kevin Hart | short, comedian, Philadelphia, Jumanji',
    'Keanu Reeves | John Wick, Matrix, nice guy, Neo',
    'Leonardo DiCaprio | Titanic, Oscar, Inception, Jack',
    'Brad Pitt | Fight Club, Ocean’s Eleven, Angelina, handsome',
    'Jennifer Aniston | Friends, Rachel, haircut, Brad',
    'Jennifer Lopez | J.Lo, Jenny from the Block, Bronx, Super Bowl',
    'Oprah | talk show, you get a car, Winfrey, book club',
    'Jimmy Fallon | Tonight Show, late night, SNL, laughing',
    'Gordon Ramsay | chef, idiot sandwich, Hell’s Kitchen, shouting',
    'Martha Stewart | homemaking, Snoop Dogg, crafts, baking',
    'Kim Kardashian | Kris Jenner, Skims, reality star, law school',
    'Kylie Jenner | lip kits, Kardashians, makeup, billionaire',
    'Kris Jenner | momager, Kardashians, mom, you’re doing amazing sweetie',
    'Paris Hilton | that’s hot, heiress, Simple Life, chihuahua',
    'Pedro Pascal | Mandalorian, The Last of Us, Narcos, Chilean',
    'Sydney Sweeney | Euphoria, Anyone But You, White Lotus, Cassie',
    'Jenna Ortega | Wednesday, Addams, Scream, dance',
    'Millie Bobby Brown | Eleven, Stranger Things, Enola Holmes, British',
    'Florence Pugh | Midsommar, Little Women, Black Widow, British',
    'Austin Butler | Elvis, Dune, accent, Baz Luhrmann',
    'Jacob Elordi | Euphoria, Saltburn, Elvis, Australian',
    'Glen Powell | Top Gun, Hit Man, Twisters, Anyone But You',
    'Pete Davidson | SNL, Staten Island, tattoos, comedian',
    'Adam Sandler | basketball shorts, Happy Gilmore, Grown Ups, Netflix',
    'Will Ferrell | Elf, Anchorman, SNL, Step Brothers',
    'Steve Carell | Michael Scott, The Office, Despicable Me, Gru',
    'Jim Carrey | The Mask, Ace Ventura, rubber face, Grinch',
    'Jack Black | School of Rock, Tenacious D, Kung Fu Panda, Steve',
    'John Cena | you can’t see me, wrestler, Peacemaker, invisible',
    'Danny DeVito | Frank Reynolds, short, It’s Always Sunny, Penguin',
    'Jason Momoa | Aquaman, Khal Drogo, tall, Hawaiian',
    'Chris Hemsworth | Thor, Australian, hammer, Marvel',
    'Chris Evans | Captain America, Marvel, shield, Knives Out sweater',
    'Chris Pratt | Star-Lord, Parks and Rec, Andy, Jurassic World',
    'Scarlett Johansson | Black Widow, Marvel, Lost in Translation, Her',
    'Robert Downey Jr. | Iron Man, Tony Stark, Sherlock, Oppenheimer',
    'Tom Cruise | Top Gun, Mission Impossible, stunts, running',
    'Tom Hanks | Forrest Gump, Woody, Cast Away, Wilson',
    'Morgan Freeman | voice, narrator, God, Shawshank',
    'Samuel L. Jackson | Nick Fury, Pulp Fiction, snakes, Marvel',
    'Denzel Washington | Training Day, Oscar, Equalizer, actor',
    'Meryl Streep | Devil Wears Prada, Mamma Mia, Oscars, Miranda',
    'Emma Watson | Hermione, Harry Potter, Belle, British',
    'Daniel Radcliffe | Harry Potter, glasses, scar, British',
    'Hailey Bieber | Rhode, Justin, glazed donut skin, model',
    'Gigi Hadid | model, Bella, runway, Zayn',
    'Bella Hadid | model, Gigi, runway, sister',
    'Kendall Jenner | model, Kardashians, runway, 818',
    'Bob Ross | happy little trees, painter, afro, Joy of Painting',
    'Mr. Rogers | neighbourhood, cardigan, kind, won’t you be my neighbor',
    'Steve Irwin | Crocodile Hunter, crikey, Australia, khaki',
    'Bill Nye | Science Guy, bow tie, experiments, TV',
    'David Attenborough | nature documentaries, voice, Planet Earth, British',
    'Guy Fieri | Flavortown, frosted tips, Diners Drive-Ins and Dives, flames',
    'Simon Cowell | judge, American Idol, X Factor, mean',
    'Ryan Seacrest | host, American Idol, New Year’s Eve, radio',
    'Jimmy Kimmel | late night, Oscars host, mean tweets, talk show',
    'Conan O’Brien | red hair, late night, tall, podcast',
    'Tina Fey | Mean Girls, 30 Rock, SNL, Liz Lemon',
    'Amy Poehler | Leslie Knope, SNL, Parks and Rec, Inside Out',
    'Mindy Kaling | The Office, Kelly Kapoor, Never Have I Ever, writer',
    'Jennifer Lawrence | Katniss, Hunger Games, falling at the Oscars, J-Law',
    'Anne Hathaway | Princess Diaries, Devil Wears Prada, Andy, Genovia',
    'Sandra Bullock | Speed, Miss Congeniality, Gravity, The Blind Side',
    'Julia Roberts | Pretty Woman, smile, Notting Hill, Erin Brockovich',
    'Reese Witherspoon | Elle Woods, Legally Blonde, book club, Big Little Lies',
    'Angelina Jolie | Maleficent, Lara Croft, Brad Pitt, lips',
    'Viola Davis | Annalise, Oscar, The Help, EGOT',
    'Michael B. Jordan | Creed, Killmonger, Black Panther, boxing',
    'Idris Elba | Luther, British, DJ, The Wire',
    'Vin Diesel | Fast & Furious, family, bald, Groot',
    'Jackie Chan | kung fu, stunts, Rush Hour, Hong Kong',
    'Arnold Schwarzenegger | Terminator, I’ll be back, bodybuilder, governor',
    'Harrison Ford | Indiana Jones, Han Solo, grumpy, whip',
    'Hugh Jackman | Wolverine, Greatest Showman, Australian, claws',
    'Melissa McCarthy | Bridesmaids, comedian, Spy, Ursula',
    'MrBeast | YouTube, challenges, Jimmy, Feastables',
    'IShowSpeed | streamer, Ronaldo, barking, backflips',
    'Kai Cenat | streamer, Twitch, Mafiathon, Bronx',
    'Charli D’Amelio | TikTok, dancer, Renegade, Dunkin',
    'Addison Rae | TikTok, dancer, He’s All That, pop',
    'Emma Chamberlain | YouTube, coffee, vlogs, Met Gala',
    'Alix Earle | TikTok, Miami, GRWM, influencer',
    'Khaby Lame | TikTok, shrug, hands, life hacks',
    'PewDiePie | YouTube, Swedish, gaming, subscribe',
    'Markiplier | YouTube, gaming, mustache, FNAF',
    'Dude Perfect | trick shots, YouTube, bottle flip, Texas',
    'Ninja | Fortnite, Twitch, blue hair, headband',
    'Queen Elizabeth II | crown, corgis, Buckingham Palace, monarch',
    'Prince Harry | Meghan, Spare, ginger, royal',
    'Albert Einstein | E=mc², genius, crazy hair, relativity',
    'Marilyn Monroe | white dress, blonde, Happy Birthday Mr. President, icon',
    'Leonardo da Vinci | Mona Lisa, painter, inventor, Renaissance',
  ],
};
