module.exports = {
  slug: 'college-life',
  name: 'College Life',
  description: 'Dorms, deadlines and the dining hall. Everyone has a story for at least half of these.',
  accentColor: '#FFE500',
  tags: ['college', 'school'],
  createdAt: '2026-10-07T20:00:00Z',
  updatedAt: '2026-10-07T20:00:00Z',
  cards: [
    'Dorm room | bed, roommate, residence, small',
    'Roommate | share, room, live with, dorm',
    'All-nighter | stay up, sleep, study, coffee',
    'Group project | team, assignment, lazy, slides',
    'Ramen noodles | cheap, instant, packet, broke',
    'Dining hall | food, cafeteria, meal plan, trays',
    'Office hours | professor, visit, questions, time',
    'Syllabus | course, outline, first day, schedule',
    'Spring break | vacation, beach, March, holiday',
    'Finals week | exams, stress, study, end of term',
    'Lecture hall | big, room, seats, professor',
    'Student loans | debt, money, borrow, pay back',
    'Graduation | cap, gown, diploma, ceremony',
    'Homecoming | football, dance, alumni, king',
    'Laundry day | wash, clothes, quarters, machine',
    'Campus tour | guide, walk, backwards, visit',
    'Freshman year | first, new, orientation, start',
    'Textbook | expensive, read, heavy, class',
    'Library | books, quiet, study, shush',
    'Coffee run | Starbucks, caffeine, order, walk',
    'Meal plan | swipes, dining hall, food, card',
    'Study abroad | country, semester, travel, exchange',
    'Club fair | sign up, societies, tables, join',
    'Resident advisor | RA, floor, dorm, rules',
    'Move-in day | boxes, parents, dorm, carry',
    'Pop quiz | surprise, test, short, teacher',
    'GPA | grades, average, 4.0, transcript',
    'Major | subject, degree, study, choose',
    'Study group | together, exam, notes, friends',
    'Internship | job, summer, experience, unpaid',
    'Career fair | jobs, booths, resume, recruiters',
    'Tuition | fees, pay, expensive, college',
    'Professor | teacher, lecture, PhD, class',
    'Thesis | essay, long, research, final',
    'Bunk beds | top, bottom, ladder, sleep',
    'Mini fridge | small, cold, dorm, drinks',
    'Microwave dinner | heat up, ready meal, quick, frozen',
    'Fire drill | alarm, outside, evacuate, practice',
    '8 a.m. class | early, morning, tired, alarm',
    'Skipping class | miss, lecture, sleep in, attendance',
    'Cramming | study, last minute, exam, memorise',
    'Plagiarism | copy, cheating, essay, sources',
    'Extension | deadline, more time, essay, ask',
    'Rate My Professor | reviews, website, chili pepper, grades',
    'Student ID | card, photo, campus, swipe',
    'Campus squirrel | tree, nuts, bold, fluffy',
    'Laptop sticker | decal, cover, stick, Mac',
    'Hoodie | sweatshirt, hood, university, merch',
    'Scantron | bubble, pencil, test, scan',
    'Hackathon | coding, overnight, team, build',
  ],
};
