module.exports = {
  slug: 'college-life',
  name: 'College Life',
  description: 'Dorms, deadlines and the dining hall. Everyone has a story for at least half of these.',
  accentColor: '#FFE500',
  emoji: '🎓',
  tags: ['college', 'school'],
  createdAt: '2026-10-07T20:00:00Z',
  updatedAt: '2026-10-07T22:00:00Z',
  cards: [
    'Dorm room | bed, roommate, residence, small',
    'Roommate | share, room, live with, dorm',
    'All-nighter | stay up, sleep, study, coffee',
    'Group project | team, assignment, lazy, slides',
    'Ramen noodles | cheap, instant, packet, broke',
    'Dining hall | food, cafeteria, meal plan, trays',
    'Office hours | professor, visit, questions, time',
    'Syllabus | course, outline, first day, schedule',
    'Spring break | vacation, beach, March, holiday',
    'Finals week | exams, stress, study, end of term',
    'Lecture hall | big, room, seats, professor',
    'Student loans | debt, money, borrow, pay back',
    'Graduation | cap, gown, diploma, ceremony',
    'Homecoming | football, dance, alumni, king',
    'Laundry day | wash, clothes, quarters, machine',
    'Campus tour | guide, walk, backwards, visit',
    'Freshman year | first, new, orientation, start',
    'Textbook | expensive, read, heavy, class',
    'Library | books, quiet, study, shush',
    'Coffee run | Starbucks, caffeine, order, walk',
    'Meal plan | swipes, dining hall, food, card',
    'Study abroad | country, semester, travel, exchange',
    'Club fair | sign up, societies, tables, join',
    'Resident advisor | RA, floor, dorm, rules',
    'Move-in day | boxes, parents, dorm, carry',
    'Pop quiz | surprise, test, short, teacher',
    'GPA | grades, average, 4.0, transcript',
    'Major | subject, degree, study, choose',
    'Study group | together, exam, notes, friends',
    'Internship | job, summer, experience, unpaid',
    'Career fair | jobs, booths, resume, recruiters',
    'Tuition | fees, pay, expensive, college',
    'Professor | teacher, lecture, PhD, class',
    'Thesis | essay, long, research, final',
    'Bunk beds | top, bottom, ladder, sleep',
    'Mini fridge | small, cold, dorm, drinks',
    'Microwave dinner | heat up, ready meal, quick, frozen',
    'Fire drill | alarm, outside, evacuate, practice',
    '8 a.m. class | early, morning, tired, alarm',
    'Skipping class | miss, lecture, sleep in, attendance',
    'Cramming | study, last minute, exam, memorise',
    'Plagiarism | copy, cheating, essay, sources',
    'Extension | deadline, more time, essay, ask',
    'Rate My Professor | reviews, website, chili pepper, grades',
    'Student ID | card, photo, campus, swipe',
    'Campus squirrel | tree, nuts, bold, fluffy',
    'Laptop sticker | decal, cover, stick, Mac',
    'Hoodie | sweatshirt, hood, university, merch',
    'Scantron | bubble, pencil, test, scan',
    'Hackathon | coding, overnight, team, build',
    'Midterms | exams, middle, semester, stress',
    'Group chat | texts, friends, messages, muted',
    'Zoom class | online, camera off, mute, remote',
    'Dropping a class | withdraw, deadline, course, quit',
    'Financial aid | FAFSA, money, grants, tuition',
    'Scholarship | money, award, essay, free',
    'Campus job | work-study, paycheck, part-time, library',
    'Sorority | Greek life, sisters, rush, letters',
    'Fraternity | Greek life, brothers, house, letters',
    'Rush week | Greek life, recruitment, bid, pledge',
    'Intramurals | sports, teams, dodgeball, league',
    'The quad | lawn, center, frisbee, grass',
    'Student union | food court, center, hangout, building',
    'Campus bookstore | textbooks, hoodies, merch, overpriced',
    'Parking ticket | car, fine, meter, campus police',
    'Shower shoes | flip-flops, dorm bathroom, feet, gross',
    'Communal bathroom | shared, dorm, showers, floor',
    'Quiet hours | noise, dorm, RA, silence',
    'Care package | mom, snacks, box, mail',
    'Flashcards | study, memorise, cards, Quizlet',
    'Highlighter | yellow, marker, textbook, notes',
    'Canvas | assignments, portal, grades, online',
    'Turnitin | plagiarism, essay, upload, checker',
    'Word count | essay, minimum, pages, padding',
    'Due at midnight | deadline, 11:59, submit, last minute',
    'Teaching assistant | TA, grader, section, grad student',
    'Lab partner | science, experiment, goggles, team',
    'Organic chemistry | orgo, pre-med, hard, molecules',
    'Pre-med | doctor, MCAT, biology, hospital',
    'Gap year | travel, break, before college, backpacking',
    'Commuter student | drive, home, parking, bus',
    'Transfer student | new school, credits, switch, community college',
    'Graduation cap | mortarboard, decorate, tassel, toss',
    'LinkedIn | network, jobs, profile, connections',
    'Networking event | business cards, handshake, recruiters, jobs',
    'Alumni | graduates, donate, reunion, old students',
    'Tailgate | parking lot, football, grill, game day',
    'College mascot | costume, school spirit, cheer, game',
    'College acceptance letter | admitted, envelope, congrats, dream school',
    'Waitlist | maybe, admissions, wait, pending',
    'Campus visit | tour, prospective, parents, admissions',
    'Late-night pizza | delivery, 2am, study fuel, dorm',
    'Thanksgiving break | home, turkey, November, family',
    'Winter break | holidays, home, December, no classes',
    'Move-out day | boxes, dorm, end of year, parents',
    'Off-campus apartment | rent, roommates, landlord, lease',
    'Sublet | summer, rent, apartment, lease',
    'Professor’s pet | teacher, favourite, suck-up, front row',
    'Front row | seats, eager, lecture, close',
    'Bluebook | exam, essay, blue, handwritten',
  ],
};
