module.exports = {
  slug: 'films',
  name: 'Movie Night',
  description: 'Blockbusters, Pixar, rom-coms and the ones everyone quotes. If you haven’t seen it, you’ve seen the memes.',
  accentColor: '#FF3D8B',
  emoji: '🍿',
  tags: ['film', 'classics'],
  createdAt: '2026-07-26T18:00:00Z',
  updatedAt: '2026-10-07T22:00:00Z',
  cards: [
    'Barbie | Margot Robbie, Ken, pink, doll',
    'Jurassic Park | dinosaur, island, T. rex, Spielberg',
    'The Lion King | Simba, Disney, Mufasa, Africa',
    'Titanic | ship, iceberg, Jack, Rose',
    'Jaws | shark, beach, bigger boat, ocean',
    'Star Wars | Jedi, Darth Vader, Force, lightsaber',
    'The Matrix | Neo, red pill, Keanu, simulation',
    'Forrest Gump | Tom Hanks, run, box of chocolates, bench',
    'Home Alone | Kevin, burglars, Christmas, Macaulay',
    'Shrek | ogre, Donkey, swamp, Fiona',
    'Frozen | Elsa, Anna, Let It Go, Olaf',
    'Rocky | boxing, Stallone, Philadelphia, steps',
    "Ghostbusters | ghosts, who you gonna call, proton pack, slime",
    'The Godfather | mafia, Corleone, offer, Brando',
    'Toy Story | Woody, Buzz, Pixar, Andy',
    'Grease | Danny, Sandy, Travolta, musical',
    'Back to the Future | DeLorean, Marty, Doc, time travel',
    'Finding Nemo | Dory, clownfish, Pixar, ocean',
    'The Wizard of Oz | Dorothy, yellow brick road, Toto, witch',
    'Pulp Fiction | Tarantino, Travolta, dance, briefcase',
    'Mean Girls | Plastics, pink, Wednesdays, Regina',
    'Die Hard | Bruce Willis, Christmas, tower, McClane',
    'Top Gun | Maverick, Tom Cruise, jets, pilot',
    'Jumanji | board game, jungle, dice, Robin Williams',
    "The Shining | Jack Nicholson, hotel, here's Johnny, twins",
    'E.T. | alien, phone home, bicycle, Spielberg',
    'Men in Black | aliens, Will Smith, suits, sunglasses',
    'The Truman Show | Jim Carrey, TV, fake, dome',
    'Gladiator | Russell Crowe, Rome, arena, Maximus',
    'Spider-Man | web, Peter Parker, Marvel, superhero',
    'Bridesmaids | wedding, Kristen Wiig, bride, dress',
    'Cast Away | Tom Hanks, Wilson, island, volleyball',
    'Napoleon Dynamite | Vote for Pedro, llama, dance, tater tots',
    'The Hangover | Vegas, wolfpack, tiger, Bradley Cooper',
    'Legally Blonde | Elle Woods, Harvard, pink, lawyer',
    'Kill Bill | Uma Thurman, sword, yellow, Tarantino',
    'Zoolander | model, Blue Steel, Ben Stiller, Derek',
    'Beetlejuice | say it three times, ghost, Michael Keaton, stripes',
    'The Sixth Sense | I see dead people, Bruce Willis, twist, ghosts',
    'Hocus Pocus | witches, Halloween, Sanderson, Bette Midler',
    'Oppenheimer | atomic bomb, Cillian Murphy, Nolan, physicist',
    'Into the Spider-Verse | Miles Morales, animated, multiverse, Gwen',
    'Inside Out | emotions, Joy, Sadness, Pixar',
    'Encanto | Bruno, Madrigal, magic house, Colombia',
    'Moana | ocean, Maui, demigod, How Far I’ll Go',
    'Coco | Day of the Dead, guitar, Miguel, Remember Me',
    'Up | balloons, house, Carl, Russell',
    'The Avengers | Marvel, Iron Man, Hulk, superheroes',
    'Black Panther | Wakanda, Chadwick Boseman, T’Challa, Marvel',
    'Iron Man | Tony Stark, suit, Robert Downey Jr., Marvel',
    'Avatar | blue, Pandora, Na’vi, James Cameron',
    'Dune | desert, sandworm, Timothée Chalamet, spice',
    'Interstellar | space, black hole, Matthew McConaughey, Nolan',
    'Inception | dreams, spinning top, DiCaprio, Nolan',
    'The Dark Knight | Batman, Joker, Heath Ledger, Gotham',
    'Get Out | Jordan Peele, sunken place, horror, teacup',
    'La La Land | Ryan Gosling, Emma Stone, jazz, Los Angeles',
    'Harry Potter | wizard, Hogwarts, scar, Voldemort',
    'The Lord of the Rings | hobbit, Frodo, Gandalf, precious',
    'Pirates of the Caribbean | Jack Sparrow, Johnny Depp, Black Pearl, ship',
    'The Incredibles | superheroes, family, Edna, Pixar',
    'Monsters, Inc. | Sully, Mike, scream, Boo',
    'Cars | Lightning McQueen, race, Pixar, Ka-chow',
    'Madagascar | zoo, lion, penguins, I like to move it',
    'The Notebook | Ryan Gosling, love story, rain, Allie',
    'Clueless | Cher, Beverly Hills, as if, plaid',
    '10 Things I Hate About You | Heath Ledger, high school, poem, Kat',
    "She's the Man | Amanda Bynes, soccer, disguise, Channing Tatum",
    'The Princess Diaries | Anne Hathaway, Genovia, royal, Julie Andrews',
    'High School Musical | Troy, Gabriella, Wildcats, Disney',
    'Superbad | Michael Cera, Jonah Hill, McLovin, high school',
    'Step Brothers | Will Ferrell, bunk beds, John C. Reilly, Catalina',
    'Elf | Will Ferrell, Christmas, Buddy, North Pole',
    'The Grinch | green, Whoville, Christmas, Max',
    'Mamma Mia! | ABBA, Greece, Meryl Streep, wedding',
    'Pitch Perfect | a cappella, Barden Bellas, Anna Kendrick, Fat Amy',
    'Everything Everywhere All at Once | multiverse, bagel, Michelle Yeoh, hot dog fingers',
    'Wicked | Elphaba, green, Glinda, Ariana Grande',
    'Knives Out | whodunit, Benoit Blanc, Daniel Craig, sweater',
    'The Social Network | Facebook, Mark Zuckerberg, Harvard, Jesse Eisenberg',
    'Deadpool | Ryan Reynolds, red suit, Marvel, chimichangas',
    'Guardians of the Galaxy | Groot, Star-Lord, Rocket, mixtape',
    'Wonder Woman | Gal Gadot, lasso, Amazon, DC',
    'The Lego Movie | Emmet, Everything Is Awesome, bricks, Batman',
    'Zootopia | Judy Hopps, rabbit, fox, sloth',
    'Tangled | Rapunzel, hair, tower, frying pan',
    'Despicable Me | Gru, Minions, villain, moon',
    "Ferris Bueller's Day Off | skipping school, Chicago, parade, Matthew Broderick",
    'Scream | Ghostface, horror, mask, phone call',
    'It | Pennywise, clown, balloon, Stephen King',
    'John Wick | Keanu Reeves, dog, assassin, pencil',
    'Lilo & Stitch | alien, Hawaii, ohana, blue',
    'Mission: Impossible | Tom Cruise, spy, stunts, self-destruct',
    'James Bond | 007, spy, tuxedo, MI6',
    'Indiana Jones | whip, hat, archaeologist, Harrison Ford',
    'Space Jam | Michael Jordan, Looney Tunes, basketball, Bugs Bunny',
    'The Parent Trap | twins, Lindsay Lohan, summer camp, swap',
    '13 Going on 30 | Jennifer Garner, birthday wish, Thriller, magazine',
    'Bring It On | cheerleading, Kirsten Dunst, rivals, routine',
    'Crazy Rich Asians | Singapore, wedding, Constance Wu, Henry Golding',
  ],
};
