module.exports = {
  slug: 'films',
  name: 'Films Everyone Knows',
  description: 'If someone in the room has not seen it, they have at least heard of it.',
  accentColor: '#FF3D8B',
  tags: ['film', 'classics'],
  createdAt: '2026-07-26T18:00:00Z',
  updatedAt: '2026-10-07T20:00:00Z',
  cards: [
    'Jurassic Park | dinosaur, island, T. rex, Spielberg',
    'The Lion King | Simba, Disney, Mufasa, Africa',
    'Titanic | ship, iceberg, Jack, Rose',
    'Jaws | shark, beach, bigger boat, ocean',
    'Star Wars | Jedi, Darth Vader, Force, lightsaber',
    'The Matrix | Neo, red pill, Keanu, simulation',
    'Forrest Gump | Tom Hanks, run, box of chocolates, bench',
    'Home Alone | Kevin, burglars, Christmas, Macaulay',
    'Shrek | ogre, Donkey, swamp, Fiona',
    'Frozen | Elsa, Anna, Let It Go, Olaf',
    'Rocky | boxing, Stallone, Philadelphia, steps',
    "Ghostbusters | ghosts, who you gonna call, proton pack, slime",
    'The Godfather | mafia, Corleone, offer, Brando',
    'Toy Story | Woody, Buzz, Pixar, Andy',
    'Grease | Danny, Sandy, Travolta, musical',
    'Back to the Future | DeLorean, Marty, Doc, time travel',
    'Finding Nemo | Dory, clownfish, Pixar, ocean',
    'The Wizard of Oz | Dorothy, yellow brick road, Toto, witch',
    'Pulp Fiction | Tarantino, Travolta, dance, briefcase',
    'Alien | space, Ripley, Sigourney Weaver, spaceship',
    'Mean Girls | Plastics, pink, Wednesdays, Regina',
    'Die Hard | Bruce Willis, Christmas, tower, McClane',
    'The Sound of Music | nuns, Maria, hills, Von Trapp',
    'Top Gun | Maverick, Tom Cruise, jets, pilot',
    'Mrs Doubtfire | Robin Williams, nanny, disguise, dad',
    'Jumanji | board game, jungle, dice, Robin Williams',
    'Casablanca | Bogart, Rick, play it again, Morocco',
    "The Shining | Jack Nicholson, hotel, here's Johnny, twins",
    'E.T. | alien, phone home, bicycle, Spielberg',
    'Men in Black | aliens, Will Smith, suits, sunglasses',
    'Dirty Dancing | Baby, Patrick Swayze, lift, corner',
    'Groundhog Day | Bill Murray, repeat, February, loop',
    'The Truman Show | Jim Carrey, TV, fake, dome',
    'Gladiator | Russell Crowe, Rome, arena, Maximus',
    'Spider-Man | web, Peter Parker, Marvel, superhero',
    'Bridesmaids | wedding, Kristen Wiig, bride, dress',
    'Cast Away | Tom Hanks, Wilson, island, volleyball',
    'Napoleon Dynamite | Vote for Pedro, llama, dance, tater tots',
    'The Hangover | Vegas, wolfpack, tiger, Bradley Cooper',
    'Free Willy | whale, orca, jump, boy',
    'Legally Blonde | Elle Woods, Harvard, pink, lawyer',
    'Speed | bus, bomb, Keanu, Sandra Bullock',
    'Kill Bill | Uma Thurman, sword, yellow, Tarantino',
    'Zoolander | model, Blue Steel, Ben Stiller, Derek',
    'Twister | tornado, storm, cow, chasers',
    'Beetlejuice | say it three times, ghost, Michael Keaton, stripes',
    'The Sixth Sense | I see dead people, Bruce Willis, twist, ghosts',
    'Coming to America | Eddie Murphy, prince, Zamunda, Queens',
    'Big | Tom Hanks, piano, wish, grown-up',
    'Hocus Pocus | witches, Halloween, Sanderson, Bette Midler',
  ],
};
