module.exports = {
  slug: 'gen-z-slang',
  name: 'Gen Z Slang',
  description: 'Explain it without saying it. Harder than it sounds, and the older people in the room are in trouble.',
  accentColor: '#E040FB',
  emoji: '💅',
  tags: ['slang', 'internet'],
  createdAt: '2026-10-07T20:00:00Z',
  updatedAt: '2026-10-07T22:00:00Z',
  cards: [
    'Rizz | charm, flirt, game, charisma',
    'No cap | lie, serious, truth, for real',
    'Bussin | delicious, food, tasty, good',
    'Slay | queen, killed it, amazing, outfit',
    "It's giving | vibe, energy, looks like, serving",
    'Delulu | delusional, dream, fantasy, crazy',
    'Main character | protagonist, star, movie, energy',
    'NPC | game, robot, background, character',
    'The ick | gross, turn-off, cringe, ew',
    'Glow up | transformation, better, before, after',
    'Touch grass | outside, online, offline, nature',
    'Mid | average, okay, meh, middle',
    'Lowkey | secretly, quiet, kind of, highkey',
    'Vibe check | mood, energy, test, feel',
    'GOAT | greatest, all time, best, animal',
    'Ratio | replies, likes, tweet, more',
    'Stan | fan, obsessed, Eminem, support',
    'Sheesh | wow, impressive, long, drip',
    'Bruh | bro, really, disappointed, dude',
    'Caught in 4K | camera, proof, busted, video',
    'Understood the assignment | nailed it, did well, task, perfect',
    'Era | phase, period, Taylor Swift, current',
    'Side-eye | look, judging, glance, suspicious',
    'Red flag | warning, bad sign, dating, danger',
    'Gatekeep | share, secret, keep, hide',
    'FOMO | missing out, fear, party, left out',
    'Rent free | head, thinking, can’t stop, live',
    'Spill the tea | gossip, tell, drama, news',
    'Shook | shocked, surprised, stunned, scared',
    'Cringe | awkward, embarrassing, ew, uncomfortable',
    'Aura | points, energy, vibe, presence',
    'Brainrot | scrolling, TikTok, brain, memes',
    'Sigma | alpha, lone wolf, male, grindset',
    'Mewing | jawline, tongue, face, quiet',
    'Fanum tax | steal, food, bite, streamer',
    'Simp | crush, devoted, too much, nice',
    'Ghosting | disappear, ignore, texts, vanish',
    'Beige flag | quirk, harmless, warning, weird',
    'Flex | show off, brag, muscles, money',
    'Salty | bitter, upset, sore loser, annoyed',
    'Yeet | throw, toss, launch, hard',
    'Bet | okay, deal, sure, agree',
    'Periodt | end, final, period, that’s it',
    'Iykyk | if you know, inside joke, secret, letters',
    'Big yikes | awkward, bad, oops, cringe',
    'Drip | outfit, style, clothes, fresh',
    'Hits different | special, better, unique, feel',
    'Valid | fair, legit, true, okay',
    'Unhinged | crazy, wild, chaotic, out of control',
    'Roman Empire | thinking about, often, history, men',
    'Bestie | best friend, BFF, girl, babe',
    'Slaps | song, banger, good, hits',
    'Goated | greatest, best, legend, GOAT',
    'Mother | iconic, queen, slay, served',
    'Ate and left no crumbs | slayed, perfect, killed it, devoured',
    'Snatched | waist, looking good, fit, outfit',
    'Sus | suspicious, Among Us, sketchy, impostor',
    'Pookie | cute, nickname, babe, sweetie',
    'Girlboss | hustle, CEO, girl power, gaslight',
    'Gaslight | lie, manipulate, crazy, gatekeep',
    'Soft launch | hint, partner, Instagram, hand',
    'Hard launch | relationship, official, post, couple',
    'Talking stage | dating, texting, not official, crush',
    'Pick-me | attention, not like other girls, boys, try hard',
    'Let him cook | wait, trust, chef, process',
    'Say less | okay, deal, got it, done',
    'Clapback | comeback, roast, reply, savage',
    'Receipts | proof, screenshots, evidence, exposed',
    'Glazing | praise, suck up, overhype, donut',
    'Yapping | talking, too much, chatter, blah blah',
    'Cottagecore | cottage, farm, aesthetic, frog',
    'Clean girl | slicked bun, minimal, makeup, aesthetic',
    'Girl dinner | snacks, plate, random food, TikTok',
    'Hot girl walk | steps, podcast, exercise, TikTok',
    'Brat summer | Charli xcx, green, party, album',
    'Cooked | done, over, finished, doomed',
    'Crashout | lose it, freak out, angry, meltdown',
    'Rage bait | angry, comments, engagement, trolling',
    'Mogging | outshine, better looking, jawline, dominate',
    'Side quest | distraction, mission, adventure, game',
    'Lore | backstory, history, story, deep',
    'Canon event | destiny, must happen, Spider-Verse, fate',
    'Opp | enemy, opponent, rival, hater',
    'On God | swear, promise, for real, truth',
    'Deadass | seriously, for real, honest, no joke',
    'Slept on | underrated, ignored, missed, overlooked',
    'Tweaking | acting crazy, wild, overreacting, bugging',
    'Bed rotting | blanket, lazy, phone, all day',
    'Feral | wild, unhinged, animal, chaotic',
    'Fit check | outfit, show, clothes, mirror',
    'Purr | yes, cat, agree, slay',
    'No thoughts, head empty | blank, dumb, clueless, vibing',
    'Sending me | funny, laughing, dying, hilarious',
    'I’m dead | laughing, funny, dying, LOL',
    'VSCO girl | scrunchie, Hydro Flask, sksksk, save the turtles',
    'E-girl | eyeliner, hearts, TikTok, pigtails',
    'Mutuals | follow each other, friends, online, followers',
    'Parasocial | one-sided, celebrity, fan, relationship',
    'Aura farming | cool, vibe, look good, points',
    'Six seven | meme, kids, numbers, hand motion',
  ],
};
