module.exports = {
  slug: 'gen-z-slang',
  name: 'Gen Z Slang',
  description: 'Explain it without saying it. Harder than it sounds, and the older people in the room are in trouble.',
  accentColor: '#E040FB',
  tags: ['slang', 'internet'],
  createdAt: '2026-10-07T20:00:00Z',
  updatedAt: '2026-10-07T20:00:00Z',
  cards: [
    'Rizz | charm, flirt, game, charisma',
    'No cap | lie, serious, truth, for real',
    'Bussin | delicious, food, tasty, good',
    'Slay | queen, killed it, amazing, outfit',
    "It's giving | vibe, energy, looks like, serving",
    'Delulu | delusional, dream, fantasy, crazy',
    'Main character | protagonist, star, movie, energy',
    'NPC | game, robot, background, character',
    'The ick | gross, turn-off, cringe, ew',
    'Glow up | transformation, better, before, after',
    'Touch grass | outside, online, offline, nature',
    'Mid | average, okay, meh, middle',
    'Lowkey | secretly, quiet, kind of, highkey',
    'Vibe check | mood, energy, test, feel',
    'GOAT | greatest, all time, best, animal',
    'Ratio | replies, likes, tweet, more',
    'Stan | fan, obsessed, Eminem, support',
    'Sheesh | wow, impressive, long, drip',
    'Bruh | bro, really, disappointed, dude',
    'Caught in 4K | camera, proof, busted, video',
    'Understood the assignment | nailed it, did well, task, perfect',
    'Era | phase, period, Taylor Swift, current',
    'Side-eye | look, judging, glance, suspicious',
    'Red flag | warning, bad sign, dating, danger',
    'Gatekeep | share, secret, keep, hide',
    'FOMO | missing out, fear, party, left out',
    'Rent free | head, thinking, can’t stop, live',
    'Spill the tea | gossip, tell, drama, news',
    'Shook | shocked, surprised, stunned, scared',
    'Cringe | awkward, embarrassing, ew, uncomfortable',
    'Aura | points, energy, vibe, presence',
    'Brainrot | scrolling, TikTok, brain, memes',
    'Sigma | alpha, lone wolf, male, grindset',
    'Mewing | jawline, tongue, face, quiet',
    'Fanum tax | steal, food, bite, streamer',
    'Simp | crush, devoted, too much, nice',
    'Ghosting | disappear, ignore, texts, vanish',
    'Beige flag | quirk, harmless, warning, weird',
    'Flex | show off, brag, muscles, money',
    'Salty | bitter, upset, sore loser, annoyed',
    'Yeet | throw, toss, launch, hard',
    'Bet | okay, deal, sure, agree',
    'Periodt | end, final, period, that’s it',
    'Iykyk | if you know, inside joke, secret, letters',
    'Big yikes | awkward, bad, oops, cringe',
    'Drip | outfit, style, clothes, fresh',
    'Hits different | special, better, unique, feel',
    'Valid | fair, legit, true, okay',
    'Unhinged | crazy, wild, chaotic, out of control',
    'Roman Empire | thinking about, often, history, men',
  ],
};
