module.exports = {
  slug: 'music-icons',
  name: 'Music Icons',
  description: 'Pop stars, rappers and legends. Humming is allowed. Singing the chorus is cheating, but everyone does it.',
  accentColor: '#00C2B2',
  emoji: '🎤',
  tags: ['music', 'pop culture'],
  createdAt: '2026-10-07T20:00:00Z',
  updatedAt: '2026-10-07T22:00:00Z',
  cards: [
    'Taylor Swift | Swifties, Eras Tour, Shake It Off, Love Story',
    "Beyoncé | Queen B, Single Ladies, Destiny's Child, Beyhive",
    'Drake | Toronto, Hotline Bling, OVO, rapper',
    'Bad Bunny | Puerto Rico, reggaeton, Spanish, Benito',
    'Billie Eilish | bad guy, Finneas, whisper, Ocean Eyes',
    'Harry Styles | One Direction, Watermelon Sugar, As It Was, British',
    'Ariana Grande | ponytail, Wicked, high notes, thank u next',
    'Olivia Rodrigo | drivers license, Sour, Disney, Guts',
    'The Weeknd | Blinding Lights, Abel, Super Bowl, Canadian',
    'Rihanna | Umbrella, Barbados, Fenty, Diamonds',
    'Kendrick Lamar | Compton, Not Like Us, Pulitzer, rapper',
    'Doja Cat | Say So, Planet Her, rapper, Mooo',
    'SZA | Kill Bill, SOS, Snooze, R&B',
    'Dua Lipa | Levitating, New Rules, Barbie, British',
    'Ed Sheeran | ginger, Shape of You, guitar, loop pedal',
    'Bruno Mars | Uptown Funk, Silk Sonic, 24K Magic, Hawaii',
    'Lady Gaga | Bad Romance, Little Monsters, meat dress, A Star Is Born',
    'Post Malone | face tattoos, Circles, Sunflower, Posty',
    'Justin Bieber | Baby, Beliebers, Canada, YouTube',
    'Adele | Hello, Someone Like You, British, ballads',
    'BTS | K-pop, ARMY, Dynamite, Korean',
    'BLACKPINK | K-pop, Jennie, Lisa, Blinks',
    "Sabrina Carpenter | Espresso, Please Please Please, Short n' Sweet, Disney",
    'Chappell Roan | Pink Pony Club, HOT TO GO, Midwest Princess, Good Luck Babe',
    'Nicki Minaj | Barbz, Super Bass, Starships, rapper',
    'Eminem | Slim Shady, Lose Yourself, 8 Mile, Detroit',
    'Megan Thee Stallion | Hotties, Savage, Houston, rapper',
    'Lil Nas X | Old Town Road, cowboy, horses, Montero',
    "Shakira | Colombia, Waka Waka, Hips Don't Lie, World Cup",
    'Miley Cyrus | Hannah Montana, Flowers, Wrecking Ball, Disney',
    'Selena Gomez | Disney, Wizards of Waverly Place, Rare Beauty, Only Murders',
    'Katy Perry | Firework, Roar, Teenage Dream, American Idol',
    'Britney Spears | Toxic, Baby One More Time, Oops, pop princess',
    'Mariah Carey | All I Want for Christmas, whistle notes, December, diva',
    'Whitney Houston | I Will Always Love You, The Bodyguard, diva, ballad',
    'ABBA | Mamma Mia, Sweden, Dancing Queen, Eurovision',
    'Queen | Freddie Mercury, Bohemian Rhapsody, We Will Rock You, band',
    'The Beatles | Liverpool, Paul, John, Yellow Submarine',
    'Elvis Presley | King, rock and roll, Graceland, hips',
    'Madonna | Material Girl, Vogue, Queen of Pop, Like a Prayer',
    'Bob Marley | reggae, Jamaica, dreadlocks, One Love',
    'Frank Ocean | Blonde, Channel Orange, R&B, mysterious',
    'Tyler, the Creator | Odd Future, IGOR, Golf, rapper',
    'Lana Del Rey | sad, Summertime Sadness, Video Games, vintage',
    'Charli xcx | brat, green, 360, Von Dutch',
    'One Direction | boy band, Harry, Niall, X Factor',
    'Coldplay | Chris Martin, Yellow, Viva la Vida, wristbands',
    'Imagine Dragons | Radioactive, Believer, Las Vegas, band',
    'Ice Spice | Munch, Bronx, orange hair, rapper',
    'Noah Kahan | Stick Season, Vermont, folk, guitar',
    'Prince | Purple Rain, Minneapolis, symbol, purple',
    'Elton John | Rocket Man, glasses, piano, Tiny Dancer',
    'David Bowie | Ziggy Stardust, lightning bolt, Starman, glam',
    'Stevie Wonder | Superstition, harmonica, Motown, sunglasses',
    'Aretha Franklin | Respect, Queen of Soul, Detroit, gospel',
    'Dolly Parton | Jolene, country, 9 to 5, Dollywood',
    'Johnny Cash | Man in Black, country, Ring of Fire, Folsom',
    'Frank Sinatra | Ol’ Blue Eyes, My Way, crooner, Fly Me to the Moon',
    'Tupac | 2Pac, California Love, West Coast, rapper',
    'Snoop Dogg | Drop It Like It’s Hot, Martha Stewart, Long Beach, rapper',
    'Jay-Z | Hova, Beyoncé, Brooklyn, Empire State of Mind',
    'Lil Wayne | Weezy, Lollipop, New Orleans, rapper',
    'Pharrell | Happy, hat, Neptunes, Get Lucky',
    'Missy Elliott | Get Ur Freak On, Work It, Virginia, rapper',
    'Usher | Yeah!, Confessions, Super Bowl, R&B',
    "Alicia Keys | Fallin', piano, Empire State of Mind, New York",
    'Celine Dion | My Heart Will Go On, Titanic, Canada, ballad',
    "Shania Twain | Man! I Feel Like a Woman!, country, Canada, That Don't Impress Me Much",
    'Avril Lavigne | Complicated, Sk8er Boi, pop punk, Canada',
    'Paramore | Hayley Williams, Misery Business, pop punk, band',
    'Green Day | American Idiot, Billie Joe, punk, Basket Case',
    'Linkin Park | In the End, Numb, Chester, band',
    'Nirvana | Kurt Cobain, Smells Like Teen Spirit, grunge, Seattle',
    'Fall Out Boy | Sugar We’re Goin Down, Patrick Stump, emo, band',
    'My Chemical Romance | emo, Welcome to the Black Parade, Gerard Way, band',
    'Panic! at the Disco | Brendon Urie, I Write Sins, emo, High Hopes',
    'Arctic Monkeys | Do I Wanna Know, Alex Turner, British, band',
    'Maroon 5 | Adam Levine, Moves Like Jagger, band, Payphone',
    'Jonas Brothers | Nick, Joe, Kevin, Disney',
    'Backstreet Boys | I Want It That Way, Nick Carter, 90s, Everybody',
    "NSYNC | Justin Timberlake, boy band, Bye Bye Bye, It's Gonna Be Me",
    'Spice Girls | Posh, Scary, Wannabe, Baby',
    'Camila Cabello | Havana, Fifth Harmony, Señorita, Cuba',
    'Shawn Mendes | Canada, Stitches, Señorita, guitar',
    'Lorde | Royals, New Zealand, Melodrama, teenager',
    'Hozier | Take Me to Church, Irish, Too Sweet, deep voice',
    'Sam Smith | Stay With Me, Unholy, British, ballad',
    'Daddy Yankee | Gasolina, reggaeton, Despacito, Puerto Rico',
    'Karol G | Bichota, Colombia, reggaeton, blue hair',
    'Rosalía | Spain, flamenco, Motomami, Despechá',
    'Pitbull | Mr. Worldwide, bald, dale, Miami',
    'Calvin Harris | DJ, Scotland, Summer, This Is What You Came For',
    'Avicii | Wake Me Up, DJ, Levels, Sweden',
    'Daft Punk | helmets, robots, French, Get Lucky',
    'The Chainsmokers | Closer, DJ duo, Roses, EDM',
    'Kesha | TiK ToK, glitter, party, dollar sign',
    'Gwen Stefani | No Doubt, Hollaback Girl, The Voice, bananas',
    'OutKast | Hey Ya!, André 3000, Atlanta, duo',
    'Childish Gambino | Donald Glover, This Is America, Redbone, rapper',
    'Cardi B | Bodak Yellow, Bronx, okurrr, rapper',
  ],
};
