/**
 * Lines to act out. The room performs the line (voice, face, the whole
 * scene) and the guesser says it back. The note is where it is from, shown in
 * the recap. No banned words: the line itself is the card.
 */
module.exports = {
  slug: 'quotes',
  name: 'Movie & TV Quotes',
  description: 'Say it like they said it. The room acts out the line, the guesser shouts it back. Accents encouraged.',
  accentColor: '#E040FB',
  emoji: '💬',
  tags: ['film', 'tv', 'acting'],
  createdAt: '2026-10-07T22:00:00Z',
  updatedAt: '2026-10-07T22:00:00Z',
  cards: [
    ["May the Force be with you", "Star Wars"],
    ["I'll be back", "The Terminator"],
    ["You can't handle the truth!", "A Few Good Men"],
    ["Here's Johnny!", "The Shining"],
    ["Houston, we have a problem", "Apollo 13"],
    ["I'm the king of the world!", "Titanic"],
    ["Life is like a box of chocolates", "Forrest Gump"],
    ["Just keep swimming", "Finding Nemo"],
    ["To infinity and beyond!", "Toy Story"],
    ["Hakuna matata", "The Lion King"],
    ["You're a wizard, Harry", "Harry Potter"],
    ["I see dead people", "The Sixth Sense"],
    ["There's no place like home", "The Wizard of Oz"],
    ["E.T. phone home", "E.T."],
    ["No, I am your father", "The Empire Strikes Back"],
    ["Show me the money!", "Jerry Maguire"],
    ["Why so serious?", "The Dark Knight"],
    ["I feel the need for speed", "Top Gun"],
    ["On Wednesdays we wear pink", "Mean Girls"],
    ["Stop trying to make fetch happen", "Mean Girls"],
    ["As if!", "Clueless"],
    ["You had me at hello", "Jerry Maguire"],
    ["Keep the change, ya filthy animal", "Home Alone"],
    ["Bond. James Bond.", "James Bond"],
    ["Wakanda forever!", "Black Panther"],
    ["I am Groot", "Guardians of the Galaxy"],
    ["I am Iron Man", "Iron Man"],
    ["Avengers, assemble!", "Avengers: Endgame"],
    ["Do you wanna build a snowman?", "Frozen"],
    ["Ohana means family", "Lilo & Stitch"],
    ["Hasta la vista, baby", "Terminator 2"],
    ["Nobody puts Baby in a corner", "Dirty Dancing"],
    ["Run, Forrest, run!", "Forrest Gump"],
    ["Wax on, wax off", "The Karate Kid"],
    ["You're gonna need a bigger boat", "Jaws"],
    ["Life, uh, finds a way", "Jurassic Park"],
    ["Freedom!", "Braveheart"],
    ["This is Sparta!", "300"],
    ["Are you not entertained?", "Gladiator"],
    ["My precious", "The Lord of the Rings"],
    ["You shall not pass!", "The Lord of the Rings"],
    ["Inconceivable!", "The Princess Bride"],
    ["We're not in Kansas anymore", "The Wizard of Oz"],
    ["Carpe diem", "Dead Poets Society"],
    ["Dobby is a free elf!", "Harry Potter"],
    ["It's LeviOsa, not LevioSA", "Harry Potter"],
    ["Ogres are like onions", "Shrek"],
    ["Do you know the Muffin Man?", "Shrek"],
    ["Why'd it have to be snakes?", "Indiana Jones"],
    ["You talkin' to me?", "Taxi Driver"],
    ["An offer he can't refuse", "The Godfather"],
    ["Bueller? Bueller?", "Ferris Bueller's Day Off"],
    ["They're here!", "Poltergeist"],
    ["Hey, you guys!", "The Goonies"],
    ["Adventure is out there!", "Up"],
    ["Squirrel!", "Up"],
    ["Fish are friends, not food", "Finding Nemo"],
    ["P. Sherman, 42 Wallaby Way, Sydney", "Finding Nemo"],
    ["Ka-chow!", "Cars"],
    ["Where's my super suit?", "The Incredibles"],
    ["No capes!", "The Incredibles"],
    ["I volunteer as tribute!", "The Hunger Games"],
    ["May the odds be ever in your favor", "The Hunger Games"],
    ["Hi Barbie! Hi Ken!", "Barbie"],
    ["I'm just Ken", "Barbie"],
    ["I'm the captain now", "Captain Phillips"],
    ["Wilson!", "Cast Away"],
    ["I'll never let go, Jack", "Titanic"],
    ["Mischief managed", "Harry Potter"],
    ["Expecto Patronum!", "Harry Potter"],
    ["I don't have friends, I got family", "Fast Five"],
    ["It's over, Anakin, I have the high ground", "Star Wars: Revenge of the Sith"],
    ["Hello there", "Star Wars: Revenge of the Sith"],
    ["Do or do not, there is no try", "The Empire Strikes Back"],
    ["It's a trap!", "Return of the Jedi"],
    ["Mr. Stark, I don't feel so good", "Avengers: Infinity War"],
    ["I can do this all day", "Captain America"],
    ["I am inevitable", "Avengers: Endgame"],
    ["Love you 3000", "Avengers: Endgame"],
    ["We were on a break!", "Friends"],
    ["How you doin'?", "Friends"],
    ["Pivot!", "Friends"],
    ["Bazinga!", "The Big Bang Theory"],
    ["D'oh!", "The Simpsons"],
    ["Winter is coming", "Game of Thrones"],
    ["Yada yada yada", "Seinfeld"],
    ["Bears. Beets. Battlestar Galactica.", "The Office"],
    ["Treat yo self!", "Parks and Recreation"],
    ["Cool cool cool cool cool", "Brooklyn Nine-Nine"],
    ["Is mayonnaise an instrument?", "SpongeBob SquarePants"],
    ["I'm ready!", "SpongeBob SquarePants"],
    ["Cowabunga!", "Teenage Mutant Ninja Turtles"],
    ["Yabba dabba doo!", "The Flintstones"],
    ["What's up, Doc?", "Looney Tunes"],
    ["Live long and prosper", "Star Trek"],
    ["Wubba lubba dub dub", "Rick and Morty"],
    ["This is the way", "The Mandalorian"],
    ["You know nothing, Jon Snow", "Game of Thrones"],
    ["Shut up and take my money!", "Futurama"],
    ["Legen—wait for it—dary!", "How I Met Your Mother"],
  ],
};
