module.exports = {
  slug: 'reality-tv',
  name: 'Reality TV',
  description: 'Villas, tribes, bake-offs and reunions. Somebody in the room has watched all of these.',
  accentColor: '#FF3D8B',
  tags: ['tv', 'pop culture'],
  createdAt: '2026-10-07T20:00:00Z',
  updatedAt: '2026-10-07T20:00:00Z',
  cards: [
    'Survivor | island, tribe, vote, torch',
    'Big Brother | house, evict, cameras, houseguests',
    'The Bachelor | rose, dating, proposal, final',
    'Love Island | villa, couples, islanders, recoupling',
    'Keeping Up with the Kardashians | Kim, Kris, family, E!',
    'The Great British Bake Off | tent, baking, Paul Hollywood, handshake',
    'Shark Tank | investors, pitch, deal, business',
    'American Idol | singing, audition, judges, Simon',
    'The Voice | spinning chairs, coaches, blind audition, singing',
    'Jersey Shore | Snooki, gym tan laundry, beach, the Situation',
    'Selling Sunset | real estate, LA, houses, Netflix',
    'Love Is Blind | pods, engaged, Netflix, dating',
    "RuPaul's Drag Race | queens, lip sync, sashay, wigs",
    'Queer Eye | Fab Five, makeover, Netflix, Jonathan',
    'Below Deck | yacht, crew, captain, charter',
    'The Real Housewives | Bravo, reunion, drama, wives',
    "Hell's Kitchen | Gordon Ramsay, chefs, raw, shouting",
    'MasterChef | cooking, judges, apron, mystery box',
    'Nailed It! | baking fails, cake, funny, Netflix',
    'Chopped | basket, mystery ingredients, chef, judges',
    'The Amazing Race | teams, pit stop, travel, world',
    "America's Got Talent | acts, golden buzzer, judges, Simon",
    'The Masked Singer | costume, mask, guess, celebrity',
    'Dance Moms | Abby Lee, pyramid, competition, mothers',
    'Married at First Sight | strangers, wedding, experts, marriage',
    'The Traitors | castle, faithfuls, banished, round table',
    'Squid Game: The Challenge | players, money, green light, Netflix',
    'Beast Games | MrBeast, contestants, prize, Amazon',
    'Physical: 100 | fitness, Korea, torso, strongest',
    'Wipeout | obstacles, big balls, fall, water',
    'American Ninja Warrior | obstacle course, warped wall, climbing, buzzer',
    'Fear Factor | eat bugs, stunts, scary, dare',
    'Cake Boss | Buddy, bakery, Hoboken, TLC',
    'Say Yes to the Dress | wedding, bride, gown, shop',
    'Toddlers & Tiaras | pageant, kids, crowns, glitz',
    'MTV Cribs | house tour, celebrity, fridge, mansion',
    'Pawn Stars | shop, sell, Las Vegas, Rick',
    'Storage Wars | auction, units, bid, lockers',
    'Fixer Upper | Chip, Joanna, renovate, Waco',
    'Catfish | fake profile, online, Nev, meet',
    'The Circle | screens, apartments, influencer, messaging',
    'Is It Cake? | realistic, cut, knife, illusion',
    'Undercover Boss | disguise, CEO, employees, company',
    'Confessional | camera, interview, alone, talk',
    'Villain edit | bad guy, producers, mean, editing',
    'Reunion episode | everyone, back, drama, host',
    'Elimination | voted off, out, leave, goodbye',
    'Plot twist | surprise, unexpected, turn, shock',
    'Tribal council | Survivor, vote, torch, Jeff Probst',
    'Cliffhanger | ending, next week, suspense, episode',
  ],
};
