module.exports = {
  slug: 'reality-tv',
  name: 'Reality TV',
  description: 'Villas, tribes, bake-offs and reunions. Somebody in the room has watched all of these.',
  accentColor: '#FF3D8B',
  emoji: '🌹',
  tags: ['tv', 'pop culture'],
  createdAt: '2026-10-07T20:00:00Z',
  updatedAt: '2026-10-07T22:00:00Z',
  cards: [
    'Survivor | island, tribe, vote, torch',
    'Big Brother | house, evict, cameras, houseguests',
    'The Bachelor | rose, dating, proposal, final',
    'Love Island | villa, couples, islanders, recoupling',
    'Keeping Up with the Kardashians | Kim, Kris, family, E!',
    'The Great British Bake Off | tent, baking, Paul Hollywood, handshake',
    'Shark Tank | investors, pitch, deal, business',
    'American Idol | singing, audition, judges, Simon',
    'The Voice | spinning chairs, coaches, blind audition, singing',
    'Jersey Shore | Snooki, gym tan laundry, beach, the Situation',
    'Selling Sunset | real estate, LA, houses, Netflix',
    'Love Is Blind | pods, engaged, Netflix, dating',
    "RuPaul's Drag Race | queens, lip sync, sashay, wigs",
    'Queer Eye | Fab Five, makeover, Netflix, Jonathan',
    'Below Deck | yacht, crew, captain, charter',
    'The Real Housewives | Bravo, reunion, drama, wives',
    "Hell's Kitchen | Gordon Ramsay, chefs, raw, shouting",
    'MasterChef | cooking, judges, apron, mystery box',
    'Nailed It! | baking fails, cake, funny, Netflix',
    'Chopped | basket, mystery ingredients, chef, judges',
    'The Amazing Race | teams, pit stop, travel, world',
    "America's Got Talent | acts, golden buzzer, judges, Simon",
    'The Masked Singer | costume, mask, guess, celebrity',
    'Dance Moms | Abby Lee, pyramid, competition, mothers',
    'Married at First Sight | strangers, wedding, experts, marriage',
    'The Traitors | castle, faithfuls, banished, round table',
    'Squid Game: The Challenge | players, money, green light, Netflix',
    'Beast Games | MrBeast, contestants, prize, Amazon',
    'Physical: 100 | fitness, Korea, torso, strongest',
    'Wipeout | obstacles, big balls, fall, water',
    'American Ninja Warrior | obstacle course, warped wall, climbing, buzzer',
    'Fear Factor | eat bugs, stunts, scary, dare',
    'Cake Boss | Buddy, bakery, Hoboken, TLC',
    'Say Yes to the Dress | wedding, bride, gown, shop',
    'Toddlers & Tiaras | pageant, kids, crowns, glitz',
    'MTV Cribs | house tour, celebrity, fridge, mansion',
    'Pawn Stars | shop, sell, Las Vegas, Rick',
    'Storage Wars | auction, units, bid, lockers',
    'Fixer Upper | Chip, Joanna, renovate, Waco',
    'Catfish | fake profile, online, Nev, meet',
    'The Circle | screens, apartments, influencer, messaging',
    'Is It Cake? | realistic, cut, knife, illusion',
    'Undercover Boss | disguise, CEO, employees, company',
    'Confessional | camera, interview, alone, talk',
    'Villain edit | bad guy, producers, mean, editing',
    'Reunion episode | everyone, back, drama, host',
    'Elimination | voted off, out, leave, goodbye',
    'Plot twist | surprise, unexpected, turn, shock',
    'Tribal council | Survivor, vote, torch, Jeff Probst',
    'Cliffhanger | ending, next week, suspense, episode',
    'The Bachelorette | roses, suitors, final, proposal',
    'Bachelor in Paradise | beach, Mexico, roses, couples',
    'Vanderpump Rules | Bravo, SUR, Lisa, Stassi',
    'Summer House | Hamptons, Bravo, friends, weekends',
    'The Challenge | MTV, eliminations, CT, competitors',
    'Project Runway | fashion, designers, Heidi Klum, make it work',
    'Top Chef | cooking, Bravo, Padma, pack your knives',
    'Kitchen Nightmares | Gordon Ramsay, restaurant, rescue, disaster',
    'Tiny House Nation | small, downsizing, home, build',
    'House Hunters | three homes, buyers, HGTV, pick one',
    'Property Brothers | twins, Drew, Jonathan, renovate',
    'Dancing with the Stars | ballroom, celebrities, mirror ball, judges',
    'So You Think You Can Dance | auditions, choreography, dancers, contest',
    'America’s Next Top Model | Tyra, smize, photo shoot, runway',
    'Alone | wilderness, survival, solo, tap out',
    'Deadliest Catch | crab, Alaska, boats, fishermen',
    'Duck Dynasty | beards, camo, Louisiana, family',
    '90 Day Fiancé | visa, K-1, love, international',
    'Hoarders | stuff, cleanup, house, piles',
    'Extreme Couponing | coupons, savings, stockpile, checkout',
    'The Ultimatum | marry or move on, couples, Netflix, swap',
    'Siesta Key | Florida, MTV, friends, beach',
    'Laguna Beach | MTV, Lauren Conrad, Orange County, Kristin',
    'The Hills | MTV, Lauren Conrad, LA, Speidi',
    "The Simple Life | Paris Hilton, Nicole Richie, farm, that's hot",
    'Selling the OC | real estate, Orange County, Netflix, agents',
    'Bling Empire | rich, Los Angeles, Netflix, luxury',
    'Lego Masters | bricks, build, Will Arnett, teams',
    'Floor Is Lava | jump, furniture, Netflix, obstacle',
    'Holey Moley | mini golf, obstacles, celebrity host, wipeout',
    'Cupcake Wars | bakers, frosting, Food Network, judges',
    'Guy’s Grocery Games | Flavortown, supermarket, cooking, shopping',
    'Worst Cooks in America | boot camp, terrible, kitchen, recruits',
    'Kids Baking Championship | children, desserts, Food Network, judges',
    'Jury Duty | fake trial, Ronald, James Marsden, prank',
    'Love on the Spectrum | dating, autism, Netflix, heartfelt',
    'Indian Matchmaking | Sima Aunty, arranged, Mumbai, Netflix',
    'American Pickers | antiques, road trip, barns, Mike and Frank',
    'Impractical Jokers | pranks, friends, punishment, hidden camera',
    'Rose ceremony | flower, Bachelor, will you accept, elimination',
    'Hometown dates | families, Bachelor, visits, parents',
    'Casa Amor | Love Island, villa, temptation, recoupling',
    'Bombshell | Love Island, new arrival, villa, entrance',
    'Hidden immunity idol | Survivor, safe, search, tribal council',
    'Head of Household | Big Brother, HOH, nominate, power',
    'Blindside | Survivor, surprise, voted out, vote',
    'Showmance | romance, show, couple, cameras',
    'Alliance | team up, strategy, Survivor, trust',
    'Golden buzzer | AGT, gold confetti, straight through, judges',
    'Season finale | last episode, ending, winner, cliffhanger',
  ],
};
