module.exports = {
  slug: 'sports',
  name: 'Sports',
  description: 'Legends, superstars and the moments everyone acts out. Slam dunks, hat tricks and the Gatorade shower.',
  accentColor: '#2EA8FF',
  emoji: '🏀',
  tags: ['sports', 'athletes'],
  createdAt: '2026-10-07T22:00:00Z',
  updatedAt: '2026-10-07T22:00:00Z',
  cards: [
    'Slam dunk | basketball, hoop, jump, rim',
    'LeBron James | Lakers, Miami, Cleveland, basketball',
    'Michael Jordan | Bulls, 23, sneakers, Space Jam',
    'Stephen Curry | Warriors, three-pointers, Golden State, night night',
    'Kobe Bryant | Lakers, Black Mamba, 24, fadeaway',
    'Shaquille O’Neal | Shaq, Lakers, huge, free throws',
    'Serena Williams | tennis, Venus, Grand Slams, GOAT',
    'Simone Biles | gymnastics, Olympics, GOAT, flips',
    'Usain Bolt | fastest man, Jamaica, lightning pose, sprinter',
    'Michael Phelps | swimming, gold medals, Olympics, Baltimore',
    'Tom Brady | Patriots, quarterback, seven rings, Buccaneers',
    'Patrick Mahomes | Chiefs, quarterback, Kansas City, ketchup',
    'Travis Kelce | Chiefs, tight end, Taylor Swift, podcast',
    'Cristiano Ronaldo | CR7, soccer, Portugal, siuuu',
    'Lionel Messi | Argentina, soccer, Inter Miami, Barcelona',
    'Kylian Mbappé | France, soccer, Real Madrid, fast',
    'David Beckham | bend it, Posh, soccer, Inter Miami',
    'Tiger Woods | golf, Masters, red shirt, Nike',
    'Muhammad Ali | boxing, float like a butterfly, the greatest, Louisville',
    'Wayne Gretzky | hockey, The Great One, 99, Canada',
    'Caitlin Clark | Iowa, WNBA, logo threes, Indiana Fever',
    'Shohei Ohtani | Dodgers, Japan, pitcher, two-way',
    'Babe Ruth | Yankees, home runs, Bambino, baseball',
    'Derek Jeter | Yankees, shortstop, captain, 2',
    'Roger Federer | tennis, Swiss, Wimbledon, elegant',
    'Rafael Nadal | tennis, Spain, clay, French Open',
    'Novak Djokovic | tennis, Serbia, Grand Slams, gluten free',
    'Coco Gauff | tennis, US Open, French Open, Florida',
    'Tony Hawk | skateboarding, 900, video game, Birdman',
    'Shaun White | snowboarding, Flying Tomato, halfpipe, red hair',
    'Victor Wembanyama | Wemby, Spurs, tall, French',
    'Luka Dončić | Lakers, Slovenia, step-back, basketball',
    'Giannis Antetokounmpo | Greek Freak, Bucks, Milwaukee, basketball',
    'Kevin Durant | KD, Warriors, slim reaper, Texas',
    'Magic Johnson | Lakers, Showtime, point guard, smile',
    'Dennis Rodman | rebounds, dyed hair, Bulls, wild',
    'Pelé | Brazil, soccer, legend, World Cups',
    'Diego Maradona | Argentina, Hand of God, soccer, 10',
    'Jackie Robinson | Dodgers, 42, baseball, barrier',
    'Jesse Owens | Olympics, 1936, sprinter, Berlin',
    'Sha’Carri Richardson | sprinter, orange hair, nails, Olympics',
    'Chloe Kim | snowboarding, halfpipe, Olympics, gold',
    'Peyton Manning | Colts, Omaha, quarterback, forehead',
    'Odell Beckham Jr. | one-handed catch, Giants, wide receiver, OBJ',
    'Megan Rapinoe | soccer, USWNT, purple hair, pose',
    'Touchdown | football, end zone, six points, score',
    'Home run | baseball, out of the park, bases, bat',
    'Hat trick | three goals, hockey, soccer, caps',
    'Hole in one | golf, single shot, ace, tee',
    'Buzzer beater | last second, shot, basketball, game winner',
    'Hail Mary | long pass, football, desperate, prayer',
    'Penalty kick | soccer, goalkeeper, spot, PK',
    'Red card | soccer, sent off, referee, foul',
    'Free throw | basketball, foul line, shot, one point',
    'Three-pointer | basketball, arc, long shot, downtown',
    'Alley-oop | lob, dunk, pass, basketball',
    'Grand slam | bases loaded, home run, baseball, tennis',
    'Strikeout | three strikes, pitcher, K, baseball',
    'Seventh-inning stretch | baseball, Take Me Out to the Ball Game, sing, stand',
    'Fantasy football | draft, league, team, Sunday',
    'March Madness | college basketball, bracket, tournament, NCAA',
    'Super Bowl | football, halftime show, commercials, February',
    'World Series | baseball, championship, October, MLB',
    'Stanley Cup | hockey, trophy, NHL, playoffs',
    'World Cup | soccer, FIFA, every four years, countries',
    'Olympics | rings, gold medal, torch, every four years',
    'Wimbledon | tennis, London, strawberries, grass',
    'Tour de France | cycling, yellow jersey, Paris, bikes',
    'Kentucky Derby | horse race, hats, Churchill Downs, roses',
    'NBA draft | picks, commissioner, hats, prospects',
    'MVP | most valuable, award, best player, chant',
    'Mascot | costume, team, cheer, furry',
    'Stadium wave | crowd, stand up, arms, ripple',
    'Jumbotron | big screen, stadium, kiss cam, replays',
    'Halftime show | Super Bowl, performance, singer, break',
    'Victory lap | run around, celebrate, track, win',
    'Photo finish | close race, camera, line, tie',
    'Instant replay | review, slow motion, referee, TV',
    'Overtime | extra time, tied, game, OT',
    'Zamboni | ice, rink, hockey, smooth',
    'Figure skating | ice, spins, jumps, Olympics',
    'Surfing | waves, board, ocean, hang ten',
    'Kickflip | skateboard, trick, flip, ollie',
    'Pickleball | paddle, court, retirees, kitchen',
    'Spikeball | net, ball, beach, roundnet',
    'Cornhole | bean bags, boards, tailgate, toss',
    'Dodgeball | school gym, throw, duck, Ben Stiller',
    'Tug of war | rope, pull, teams, mud',
    'Marathon | 26.2 miles, run, long, Boston',
    'Sumo | wrestlers, Japan, ring, push',
    'Fencing | swords, mask, touché, lunge',
    'Archery | bow, arrow, target, bullseye',
    'Curling | stone, ice, brooms, sweep',
    'Bobsled | ice track, sled, Cool Runnings, push',
    'Breakdancing | b-boy, spins, headspin, Olympics',
    'Cheerleading | pom-poms, pyramid, cheer, stunts',
    'Synchronized swimming | pool, nose clip, together, artistic',
    'Referee | whistle, stripes, ref, foul',
    'Gatorade shower | coach, bucket, celebration, win',
    'Underdog | not expected, long shot, upset, win',
  ],
};
