import throwback from '../../assets/decks/2010s-throwback.json';
import actItOut from '../../assets/decks/act-it-out.json';
import animals from '../../assets/decks/animals.json';
import animeAndGaming from '../../assets/decks/anime-and-gaming.json';
import aroundTheHouse from '../../assets/decks/around-the-house.json';
import celebrities from '../../assets/decks/celebrities.json';
import collegeLife from '../../assets/decks/college-life.json';
import emojiCharades from '../../assets/decks/emoji-charades.json';
import films from '../../assets/decks/films.json';
import foodAndDrink from '../../assets/decks/food-and-drink.json';
import genZSlang from '../../assets/decks/gen-z-slang.json';
import musicIcons from '../../assets/decks/music-icons.json';
import quotes from '../../assets/decks/quotes.json';
import realityTv from '../../assets/decks/reality-tv.json';
import snacksAndFastFood from '../../assets/decks/snacks-and-fast-food.json';
import sports from '../../assets/decks/sports.json';
import viralInternet from '../../assets/decks/viral-internet.json';

/**
 * The decks that ship with the app.
 *
 * Imported as JSON modules so Metro bundles them — no filesystem read, no
 * asset unpacking, and they are available on the very first launch offline.
 *
 * Generated by spec/generate-bundled-decks.js from the data in spec/decks.
 * Deck and card ids in these files are derived from a hash of the deck slug and
 * card text, so regenerating them is stable. A bundled deck's id must never
 * change: re-seeding matches on it, and a changed id would orphan the copy
 * already on a user's device.
 *
 * Typed as unknown deliberately. These pass through the same validator as an
 * imported deck, so a malformed bundled deck is caught by a test rather than
 * trusted because it happens to live in the repo.
 */
export const bundledDeckDocuments: readonly unknown[] = [
  films,
  animals,
  foodAndDrink,
  actItOut,
  aroundTheHouse,
  collegeLife,
  genZSlang,
  viralInternet,
  realityTv,
  musicIcons,
  animeAndGaming,
  throwback,
  snacksAndFastFood,
  emojiCharades,
  celebrities,
  sports,
  quotes,
];
