/**
 * The emoji you can search for a deck cover, with the words people type to
 * find them. Bundled, so search works offline. Anything not here can still be
 * typed straight from the keyboard.
 */

export type EmojiGroup = { name: string; emoji: readonly (readonly [string, string])[] };

export const EMOJI_GROUPS: readonly EmojiGroup[] = [
  {
    name: 'Faces',
    emoji: [
      ['😂', 'laugh crying lol funny tears joy'],
      ['🤣', 'rofl rolling laugh funny'],
      ['😜', 'wink tongue silly crazy goofy'],
      ['😎', 'cool sunglasses chill'],
      ['🥳', 'party birthday celebrate hat'],
      ['😍', 'love heart eyes crush'],
      ['🥰', 'love hearts cute adore'],
      ['😏', 'smirk sly flirt'],
      ['🤔', 'thinking hmm wonder guess'],
      ['🤫', 'shh secret quiet'],
      ['🤯', 'mind blown shocked wow'],
      ['😱', 'scream scared shock horror'],
      ['😈', 'devil evil naughty spicy'],
      ['🤡', 'clown silly circus'],
      ['👻', 'ghost boo spooky halloween'],
      ['💀', 'skull dead dying lol'],
      ['👽', 'alien ufo space'],
      ['🤖', 'robot ai tech'],
      ['💩', 'poop silly'],
      ['🙃', 'upside down silly sarcasm'],
      ['🥺', 'pleading puppy eyes please cute'],
      ['😴', 'sleep tired zzz'],
      ['🤠', 'cowboy western yeehaw'],
      ['🥸', 'disguise glasses spy'],
      ['🤓', 'nerd geek smart glasses'],
      ['😇', 'angel halo innocent'],
      ['🫠', 'melting hot awkward'],
      ['🤪', 'zany crazy wild'],
      ['😬', 'grimace awkward yikes cringe'],
      ['🙈', 'monkey see no evil embarrassed'],
    ],
  },
  {
    name: 'Party',
    emoji: [
      ['🎉', 'party popper celebrate confetti'],
      ['🎊', 'confetti ball celebrate'],
      ['🎈', 'balloon party birthday'],
      ['🎂', 'cake birthday party'],
      ['🎁', 'gift present birthday christmas'],
      ['🪩', 'disco ball dance club party'],
      ['🍾', 'champagne bottle celebrate cheers'],
      ['🥂', 'cheers toast glasses celebrate'],
      ['🎤', 'microphone karaoke sing music'],
      ['🎧', 'headphones music dj'],
      ['💃', 'dance woman salsa party'],
      ['🕺', 'dance man disco party'],
      ['🎭', 'theatre drama acting masks'],
      ['🃏', 'joker card game deck'],
      ['🎲', 'dice game random luck'],
      ['🎯', 'target bullseye darts'],
      ['🎮', 'video game controller gaming'],
      ['🕹️', 'joystick arcade retro gaming'],
      ['🧩', 'puzzle piece game'],
      ['🎰', 'slot machine casino vegas'],
      ['🎳', 'bowling'],
      ['🪅', 'pinata party'],
      ['🎆', 'fireworks new year celebrate'],
      ['✨', 'sparkles magic shiny new'],
      ['🔥', 'fire hot lit flame trending'],
      ['💥', 'boom explosion bang'],
      ['⚡', 'lightning bolt energy fast'],
      ['🌈', 'rainbow pride colourful'],
      ['💫', 'dizzy star sparkle'],
      ['🌟', 'star glowing shine'],
    ],
  },
  {
    name: 'Food',
    emoji: [
      ['🍕', 'pizza food italian slice'],
      ['🍔', 'burger hamburger food fast'],
      ['🍟', 'fries chips fast food'],
      ['🌭', 'hot dog food'],
      ['🌮', 'taco mexican food'],
      ['🌯', 'burrito wrap mexican'],
      ['🍣', 'sushi japanese fish'],
      ['🍜', 'ramen noodles soup'],
      ['🍝', 'spaghetti pasta italian'],
      ['🍦', 'ice cream dessert'],
      ['🍩', 'donut doughnut sweet'],
      ['🍪', 'cookie biscuit sweet'],
      ['🧁', 'cupcake sweet cake'],
      ['🍫', 'chocolate sweet candy'],
      ['🍬', 'candy sweet'],
      ['🍿', 'popcorn movie cinema snack'],
      ['🥨', 'pretzel snack'],
      ['🧀', 'cheese'],
      ['🥑', 'avocado guacamole'],
      ['🍓', 'strawberry fruit'],
      ['🍉', 'watermelon fruit summer'],
      ['🍌', 'banana fruit'],
      ['🍑', 'peach fruit'],
      ['🍋', 'lemon sour'],
      ['🌶️', 'chilli pepper spicy hot'],
      ['🥐', 'croissant breakfast french'],
      ['🥞', 'pancakes breakfast'],
      ['🍳', 'egg cooking breakfast'],
      ['☕', 'coffee cafe tea hot drink'],
      ['🧋', 'bubble tea boba drink'],
      ['🥤', 'soda drink cup'],
      ['🍹', 'cocktail drink tropical'],
      ['🍺', 'beer drink pub'],
      ['🍷', 'wine drink'],
      ['🧃', 'juice box drink'],
    ],
  },
  {
    name: 'Animals',
    emoji: [
      ['🐶', 'dog puppy pet'],
      ['🐱', 'cat kitty pet'],
      ['🦁', 'lion animal king'],
      ['🐯', 'tiger animal'],
      ['🐻', 'bear animal'],
      ['🐼', 'panda animal'],
      ['🐨', 'koala animal australia'],
      ['🐸', 'frog animal'],
      ['🐵', 'monkey animal'],
      ['🦊', 'fox animal'],
      ['🐰', 'bunny rabbit animal easter'],
      ['🐷', 'pig animal farm'],
      ['🐮', 'cow animal farm'],
      ['🐔', 'chicken animal farm'],
      ['🐧', 'penguin animal'],
      ['🦄', 'unicorn magic fantasy'],
      ['🐉', 'dragon fantasy'],
      ['🦖', 'dinosaur t rex'],
      ['🐙', 'octopus sea'],
      ['🦈', 'shark sea'],
      ['🐬', 'dolphin sea'],
      ['🐢', 'turtle slow'],
      ['🐝', 'bee insect'],
      ['🦋', 'butterfly insect'],
      ['🦩', 'flamingo bird pink'],
      ['🦉', 'owl bird night'],
      ['🐍', 'snake'],
      ['🦦', 'otter cute'],
      ['🦥', 'sloth slow lazy'],
      ['🐾', 'paw prints pets'],
    ],
  },
  {
    name: 'Sports',
    emoji: [
      ['🏀', 'basketball sport nba hoops'],
      ['⚽', 'football soccer sport'],
      ['🏈', 'american football nfl sport'],
      ['⚾', 'baseball sport'],
      ['🎾', 'tennis sport'],
      ['🏐', 'volleyball sport'],
      ['🏓', 'ping pong table tennis'],
      ['🏒', 'hockey ice sport'],
      ['⛳', 'golf sport'],
      ['🥊', 'boxing glove fight'],
      ['🏆', 'trophy winner champion'],
      ['🥇', 'gold medal winner first'],
      ['🏅', 'medal sport'],
      ['⛷️', 'skiing snow winter'],
      ['🏄', 'surfing beach waves'],
      ['🛹', 'skateboard skate'],
      ['🚴', 'cycling bike'],
      ['🏋️', 'gym weights lifting'],
      ['🧘', 'yoga meditate'],
      ['🏊', 'swimming pool'],
    ],
  },
  {
    name: 'Places & travel',
    emoji: [
      ['🏠', 'house home'],
      ['🏫', 'school'],
      ['🎓', 'graduation college university school'],
      ['🏖️', 'beach holiday summer vacation'],
      ['🏝️', 'island tropical holiday'],
      ['⛰️', 'mountain hiking outdoors'],
      ['🏕️', 'camping tent outdoors'],
      ['🌃', 'city night'],
      ['🗽', 'new york statue liberty usa'],
      ['🗼', 'tokyo tower japan'],
      ['🏰', 'castle fairy tale'],
      ['🎡', 'ferris wheel fair'],
      ['🎢', 'roller coaster theme park'],
      ['✈️', 'plane travel flight holiday'],
      ['🚗', 'car road trip drive'],
      ['🚀', 'rocket space launch'],
      ['🌍', 'world globe earth geography'],
      ['🗺️', 'map travel'],
      ['🌙', 'moon night'],
      ['☀️', 'sun summer hot'],
      ['❄️', 'snow cold winter'],
      ['🌊', 'wave ocean sea'],
      ['🌸', 'blossom flower spring'],
      ['🌵', 'cactus desert'],
      ['🍁', 'autumn fall leaf'],
    ],
  },
  {
    name: 'Things',
    emoji: [
      ['📱', 'phone mobile social'],
      ['💻', 'laptop computer'],
      ['📺', 'tv television show'],
      ['🎬', 'movie film clapper cinema'],
      ['📼', 'vhs tape retro 90s'],
      ['📸', 'camera photo selfie'],
      ['🎸', 'guitar music rock'],
      ['🎹', 'piano keyboard music'],
      ['🥁', 'drum music'],
      ['🎨', 'art paint artist'],
      ['📚', 'books study reading'],
      ['✏️', 'pencil write school'],
      ['💡', 'idea light bulb'],
      ['🔮', 'crystal ball magic fortune'],
      ['🪄', 'magic wand'],
      ['💎', 'diamond gem rich'],
      ['💰', 'money bag rich cash'],
      ['👑', 'crown king queen royal'],
      ['💄', 'lipstick makeup beauty'],
      ['💅', 'nails sassy slay beauty'],
      ['👟', 'sneakers trainers shoes'],
      ['🧢', 'cap hat'],
      ['🕶️', 'sunglasses cool'],
      ['🛍️', 'shopping bags'],
      ['🧸', 'teddy bear toy'],
      ['🪐', 'planet saturn space'],
      ['🧪', 'science lab chemistry'],
      ['🔬', 'microscope science'],
      ['🧠', 'brain smart think'],
      ['🗿', 'moai statue meme'],
      ['🍀', 'clover luck irish'],
      ['🎃', 'pumpkin halloween'],
      ['🎄', 'christmas tree holiday'],
      ['❤️', 'heart love red'],
      ['💔', 'broken heart breakup sad'],
      ['💯', 'hundred perfect score'],
      ['🚫', 'banned no forbidden'],
      ['❓', 'question mark mystery'],
      ['👀', 'eyes look watching'],
      ['👯', 'friends group dancers besties'],
    ],
  },
];

/** Every emoji in the catalogue, in order. */
export const ALL_EMOJI: readonly string[] = EMOJI_GROUPS.flatMap((group) => group.emoji.map(([emoji]) => emoji));

/**
 * Searches by word. Matches the start of any keyword, so "piz" finds pizza,
 * and every word typed has to match, so "red heart" narrows rather than widens.
 */
export function searchEmoji(query: string): string[] {
  const words = query.toLowerCase().trim().split(/\s+/).filter(Boolean);
  if (words.length === 0) return [...ALL_EMOJI];

  const out: string[] = [];
  for (const group of EMOJI_GROUPS) {
    for (const [emoji, keywords] of group.emoji) {
      const tags = keywords.split(' ');
      if (words.every((word) => tags.some((tag) => tag.startsWith(word)))) out.push(emoji);
    }
  }
  return out;
}

/**
 * Pulls the last emoji out of whatever was typed, so the emoji keyboard can be
 * used directly: type one, or a few, and the latest wins. Null when there is
 * no emoji in the text.
 */
export function lastEmoji(text: string): string | null {
  const matches = text.match(/\p{Extended_Pictographic}(?:️|\p{Emoji_Modifier}|‍\p{Extended_Pictographic}️?)*/gu);
  return matches?.at(-1) ?? null;
}
